---
openapi: "3.0.0"
info:
  title: "Sample IoT APIs"
  description: "These are public domain APIs, currently used for demo purpose."
  version: "1.0.0"
servers:
- url: "https://virtserver.swaggerhub.com/thirumalavenkateshc/IOTAPI/1.0.0"
  description: "SwaggerHub API Auto Mocking"
paths:
  /devices:
    get:
      tags:
      - "Device"
      description: "returns all registered devices"
      operationId: "getDevices"
      parameters:
      - name: "skip"
        in: "query"
        description: "number of records to skip"
        required: false
        style: "form"
        explode: true
        schema:
          type: "integer"
          format: "int32"
      - name: "limit"
        in: "query"
        description: "max number of records to return"
        required: false
        style: "form"
        explode: true
        schema:
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "All the devices"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "string"
                  format: "uri"
                  example: "http://10.0.0.225:8080"
    post:
      tags:
      - "Device"
      operationId: "register"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceRegistrationInfo"
      responses:
        "200":
          description: "successfully registered device"
  /lighting/dimmers/{deviceId}/{value}:
    post:
      tags:
      - "Z-Wave"
      operationId: "setDimmer"
      parameters:
      - name: "deviceId"
        in: "path"
        required: true
        style: "simple"
        explode: false
        schema:
          type: "string"
      - name: "value"
        in: "path"
        required: true
        style: "simple"
        explode: false
        schema:
          maximum: 1E+2
          minimum: 0
          type: "integer"
          format: "int32"
      responses:
        "200":
          description: "response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
      x-swagger-router-controller: "ZWave"
components:
  schemas:
    ApiResponse:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
          example: "everything is ok"
    DeviceRegistrationInfo:
      type: "object"
      properties:
        uri:
          type: "string"
          format: "uri"
          example: "http://10.0.0.220:8080"
        id:
          type: "string"
          format: "uuid"
          example: "0729a580-2240-11e6-9eb5-0002a5d5c51b"
