openapi: 2.0.0
info:
  title: Sample Library API
  description: This is a sample API
  contact:
    name: Thirumala Venkatesh C
    url: google.com
    email: thirumalavenkatesh@gmail.com
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/thirumalavenkateshc/SampleAPI/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /books:
    get:
      description: Obtain information about all the available books in the library.
      parameters:
      - name: pageLimit
        in: query
        description: Number of pages to return book information
        required: false
        style: form
        explode: true
        schema:
          maximum: 5
          minimum: 1
          type: integer
          example: 3
      responses:
        "200":
          description: Successful pull of book information.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
  /addBook:
    post:
      description: Add a new book information in library database.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: Successfully added a new book.
components:
  schemas:
    inline_response_200:
      properties:
        id:
          type: integer
          example: 2
        book name:
          type: string
          example: Luminaries
        book author:
          type: string
          example: Eleanor Catton
    body:
      type: object
      properties:
        id:
          type: integer
          example: 2
        book name:
          type: string
          example: Luminaries
        book author:
          type: string
          example: Eleanor Catton
